import { describe, it, expect } from "vitest";
import { MeteoReportSchema } from "../meteo-report.schema";
import { generateMeteoReport } from "@/src/mocks/generators";

describe("MeteoReportSchema", () => {
  it("accepts a full report generated by the MSW generator", () => {
    const report = generateMeteoReport();
    expect(() => MeteoReportSchema.parse(report)).not.toThrow();
  });

  it("parses 5 consecutive ticks without error", () => {
    for (let i = 0; i < 5; i++) {
      const report = generateMeteoReport();
      const parsed = MeteoReportSchema.parse(report);
      expect(parsed.fire_perimeter.area_ha).toBeGreaterThan(0);
      expect(parsed.prediction.hourly).toHaveLength(24);
    }
  });

  it("rejects a payload missing required fields", () => {
    const result = MeteoReportSchema.safeParse({ metadata: { model_version: "1.0.0" } });
    expect(result.success).toBe(false);
  });

  it("allows growth_rate_m2_s to be null", () => {
    const report = generateMeteoReport();
    const withNull = { ...report, prediction: { ...report.prediction, growth_rate_m2_s: null } };
    expect(() => MeteoReportSchema.parse(withNull)).not.toThrow();
  });

  it("rejects fire_weather_index as a string", () => {
    const report = generateMeteoReport();
    const bad = { ...report, prediction: { ...report.prediction, fire_weather_index: "high" } };
    const result = MeteoReportSchema.safeParse(bad);
    expect(result.success).toBe(false);
  });

  it("enforces [lon, lat] tuple for location", () => {
    const report = generateMeteoReport();
    const bad = { ...report, metadata: { ...report.metadata, location: [1, 2, 3] } };
    const result = MeteoReportSchema.safeParse(bad);
    expect(result.success).toBe(false);
  });

  it("requires risk_buffers to be an array", () => {
    const report = generateMeteoReport();
    const bad = { ...report, risk_buffers: null };
    const result = MeteoReportSchema.safeParse(bad);
    expect(result.success).toBe(false);
  });

  it("validates all 24 hourly predictions have valid hour_offset", () => {
    const report = generateMeteoReport();
    const parsed = MeteoReportSchema.parse(report);
    parsed.prediction.hourly.forEach((h, i) => {
      expect(h.hour_offset).toBe(i + 1);
    });
  });
});
